Models/Customer.cs
namespace MyShop.Models;

public class Customer
{
    public int CustomerId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Address { get; set; } = string.Empty;
    public virtual List<Order>? Orders { get; set; }
}

Models/Item.cs
using System.ComponentModel.DataAnnotations;

namespace MyShop.Models
{
	public class Item
	{
		public int ItemId { get; set; }
		public string Name { get; set; } = string.Empty;
		public decimal Price { get; set; }
		public string? Description { get; set; }
		public string? ImageUrl { get; set; }
		// navigation property
        public virtual List<OrderItem>? OrderItems { get; set; }
	}
}

Models/OrderItem.cs
namespace MyShop.Models;

public class OrderItem
{
	public int OrderItemId { get; set; }
	public int ItemId { get; set; }
	//navigation property
	public virtual Item Item { get; set; } = default!;
    public int Quantity { get; set; }
	public int OrderId { get; set; }
    //navigation property
    public virtual Order Order { get; set; } = default!;
	public decimal OrderItemPrice { get; set; }
}

ViewModels/ItemsViewModel.cs
using MyShop.Models;

namespace MyShop.ViewModels
{
    public class ItemsViewModel
    {
        public IEnumerable<Item> Items;
        public string? CurrentViewName;

        public ItemsViewModel(IEnumerable<Item> items, string? currentViewName)
        {
            Items = items;
            CurrentViewName = currentViewName;
        }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MyShop.Models;
using Microsoft.EntityFrameworkCore;
using MyShop.DAL;

namespace MyShop.Controllers;

public class CustomerController : Controller
{
    private readonly ItemDbContext _itemDbContext;

    public CustomerController(ItemDbContext itemDbContext)
    {
        _itemDbContext = itemDbContext;
    }

    public async Task<IActionResult> Table()
    {
        List<Customer> customers = await _itemDbContext.Customers.ToListAsync();
        return View(customers);
    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using MyShop.DAL;
using MyShop.Models;
using MyShop.ViewModels;

namespace MyShop.Controllers;

public class ItemController : Controller
{
    private readonly IItemRepository _itemRepository;

    public ItemController(IItemRepository itemRepository)
    {
        _itemRepository = itemRepository;
    }

    public async Task<IActionResult> Table()
    {
        var items = await _itemRepository.GetAll();
        var itemsViewModel = new ItemsViewModel(items, "Table");
        return View(itemsViewModel);
    }

    public async Task<IActionResult> Grid()
    {
        var items = await _itemRepository.GetAll();
        var itemsViewModel = new ItemsViewModel(items, "Grid");
        return View(itemsViewModel);
    }

    public async Task<IActionResult> Details(int id)
    {
        var item = await _itemRepository.GetItemById(id);
        if (item == null)
            return BadRequest("Item not found.");
        return View(item);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Item item)
    {
        if (ModelState.IsValid)
        {
            await _itemRepository.Create(item);
            return RedirectToAction(nameof(Table));
        }

        return View(item);
    }

    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        var item = await _itemRepository.GetItemById(id);
        if (item == null)
        {
            return NotFound();
        }
        return View(item);
    }

    [HttpPost]
    public async Task<IActionResult> Update(Item item)
    {
        if (ModelState.IsValid)
        {
            await _itemRepository.Update(item);
            return RedirectToAction(nameof(Table));
        }

        return View(item);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var item = await _itemRepository.GetItemById(id);
        if (item == null)
        {
            return NotFound();
        }
        return View(item);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _itemRepository.Delete(id);
        return RedirectToAction(nameof(Table));
    }
}

Views/Shared/_Carousel.cshtml
<div id="carouselImages" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item">
            <img src="~/images/pizza.jpg" class="d-block w-100" alt="Pizza">
        </div>
        <div class="carousel-item active">
            <img src="~/images/fishandchips.jpg" class="d-block w-100" alt="Fried Chicken Leg">
        </div>
        <div class="carousel-item">
            <img src="~/images/tacos.jpg" class="d-block w-100" alt="Tacos">
        </div>
    </div>
</div>

Views/Shared/_CustomerTable.cshtml
@model IEnumerable<Customer>

<div class="container">
    <table class='table table-striped'>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>Orders</th>
            <th>Actions</th>
        </tr>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.CustomerId</td>
                <td>@customer.Name</td>
                <td>@customer.Address</td>
                <td>
                    @if (@customer.Orders != null)
                    {
                        <p>@string.Join(", ", @customer.Orders.Select(order => $"Order{order.OrderId}"))</p>
                    }
                </td>
                <td></td>
            </tr>
        }
    </table>
</div>

Views/Shared/_ItemCard.cshtml
@model Item

<div class="col">
    <div>
        <img src="@Model.ImageUrl" class="card-img-top" alt="@Model.Name">
        <div>
            <div class="d-flex justify-content-between mt-2">
                <h5 class="text-start">
                    <a asp-controller="Item"
                        asp-action="Details"
                        asp-route-id="@Model.ItemId">@Model.Name</a>
                </h5>
                <h5 class="text-nowrap">
                    @Model.Price.ToString("0.00 NOK")
                </h5>
            </div>
        </div>
    </div>
</div>

Views/Shared/_ItemTable.cshtml
@model IEnumerable<Item>

<div class="container">
    <table class='table table-striped'>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Image</th>
            <th>Actions</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ItemId</td>
                <td>
                    <a asp-controller="Item"
                        asp-action="Details"
                        asp-route-id="@item.ItemId">@item.Name</a>
                </td>
                <td>@item.Price.ToString("0.00 NOK")</td>
                <td>@item.Description</td>
                <td>
                    <img src="@item.ImageUrl" alt="Item Image" style="max-width: 80px; max-height: 80px;" />
                </td>
                <td>
                    <a asp-action="Update" asp-route-id="@item.ItemId">Update</a>
                    <a asp-action="Delete" asp-route-id="@item.ItemId">Delete</a>
                </td>
            </tr>
        }
    </table>
    <p>
        <a class="btn btn-secondary"
           asp-controller="Item"
           asp-action="Create">Create New Item</a>
    </p>    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Table">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Table">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Table">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>

Views/Shared/_OrderItemTable.cshtml
@model IEnumerable<OrderItem>

<div class="container">
    <table class='table table-striped'  style='max-width: 1200px;'>
        <tr>
            <th>OrderItemId</th>
            <th>ItemId</th>
            <th>Item</th>
            <th>Quantity</th>
            <th>OrderItemPrice</th>
            <th>Actions</th>
        </tr>
        @foreach (var orderItem in Model)
        {
            <tr>
                <td>@orderItem.OrderItemId</td>
                <td>@orderItem.ItemId</td>
                <td>@orderItem.Item.Name</td>
                <td>@orderItem.Quantity</td>
                <td>@orderItem.OrderItemPrice</td>
                <td></td>
            </tr>
        }
    </table>
</div>